In [1]:
import numpy as np
import numba as nb
from numba import prange, njit

In [2]:
np.__version__, nb.__version__

('1.18.1', '0.48.0')

### Without printing

In [3]:
@njit(parallel=True)
def f1(x):

    a = np.empty(x)

    np.random.seed(0)
    for i in prange(x):
        a[i] = np.random.rand()

    print(a)

In [4]:
for i in range(3):
    f1(5)

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


### do something that is not printing

In [5]:
@njit(parallel=True)
def f2(x):

    a = np.empty(x)

    np.random.seed(0)
    for i in prange(x):
        b = i * 2
        a[i] = np.random.rand()

    print(a)

In [6]:
for i in range(3):
    f2(5)

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


### Do printing

In [7]:
@njit(parallel=True)
def f3(x):

    a = np.empty(x)

    np.random.seed(0)
    for i in prange(x):
        print(i)
        a[i] = np.random.rand()

    print(a)

In [8]:
for i in range(3):
    f3(5)

02
3

1
4
[0.5488135  0.23253631 0.42067534 0.59141705 0.11654516]
3120



4
[0.5488135  0.88699704 0.76409404 0.95652271 0.43212722]
310

4
2

[0.5488135  0.03929467 0.99941552 0.40709526 0.63220162]
