In [1]:
import numpy as np
import numba as nb
from numba import prange, njit

In [2]:
np.__version__, nb.__version__

('1.18.1', '0.48.0')

### Without printing

In [3]:
@njit(parallel=True)
def f1(x):

    a = np.empty(x)

    np.random.seed(0)
    for i in prange(x):
        a[i] = np.random.rand()

    print(a)

In [4]:
for i in range(3):
    f1(5)

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


### With printing

In [5]:
@njit(parallel=True)
def f2(x):

    a = np.empty(x)

    np.random.seed(0)
    for i in prange(x):
        print(i)
        a[i] = np.random.rand()

    print(a)

In [6]:
for i in range(3):
    f2(5)

02
1
3

4
[0.5488135  0.75318828 0.51462939 0.05391693 0.66445552]
2
0
31
4

[0.5488135  0.75756094 0.80374749 0.199746   0.46042049]
1
0
3
42

[0.5488135  0.95923902 0.16749081 0.25534706 0.62152295]
